CREATE TABLE FABRICANTE(
	CodFab VARCHAR2(10) PRIMARY KEY,
	NomFab VARCHAR2(50)
);

CREATE TABLE ARTICULO(
	CodArt VARCHAR2(10) PRIMARY KEY,
	NomArt VARCHAR2(50),
	Precio NUMBER(6,2),
	CodFab VARCHAR2(10),
	FOREIGN KEY(CodFab) REFERENCES FABRICANTE(CodFab)
);

