// default package
// Generated 7 ene 2025, 20:08:40 by Hibernate Tools 6.5.1.Final
package AD04;

import java.math.BigDecimal;
import java.sql.Date;

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private int empno;
	private int dept;
	private String ename;
	private String job;
	private Integer mgr;
	private java.util.Date hiredate;
	private double sal;
	private BigDecimal comm;

	public Emp() {
	}

	public Emp(int empno, int dept) {
		this.empno = empno;
		this.dept = dept;
	}

	public Emp(int empno, int dept, String ename, String job, Integer mgr, Date hiredate, double sal,
			BigDecimal comm) {
		this.empno = empno;
		this.dept = dept;
		this.ename = ename;
		this.job = job;
		this.mgr = mgr;
		this.hiredate = hiredate;
		this.sal = sal;
		this.comm = comm;
	}

	public int getEmpno() {
		return this.empno;
	}

	public void setEmpno(int empno) {
		this.empno = empno;
	}

	public int getDept() {
		return this.dept;
	}

	public void setDept(int i) {
		this.dept = i;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public Integer getMgr() {
		return this.mgr;
	}

	public void setMgr(Integer mgr) {
		this.mgr = mgr;
	}

	public Date getHiredate() {
		return (Date) this.hiredate;
	}

	public void setHiredate(java.util.Date date) {
		this.hiredate = date;
	}

	public double getSal() {
		return this.sal;
	}

	public void setSal(double d) {
		this.sal = d;
	}

	public BigDecimal getComm() {
		return this.comm;
	}

	public void setComm(BigDecimal comm) {
		this.comm = comm;
	}

}
