
CREATE DATABASE RestVillagarcia;
USE RestVillagarcia;

CREATE TABLE EMPLEADOS (
DNI VARCHAR(9) NOT NULL,
Nombre VARCHAR(25),
Apellidos VARCHAR(50),
Direccion VARCHAR(50),
Ciudad VARCHAR(25),
Telefono VARCHAR(9),
CP VARCHAR(5),
FechAlta DATE,
Categoria VARCHAR(25),
Salario DECIMAL(10,2),
PRIMARY KEY(DNI)
);
-- 
CREATE TABLE COCINEROS (
DNI VARCHAR(9) NOT NULL,
Puesto VARCHAR(25),
Especialidad VARCHAR(25),
PRIMARY KEY(DNI)
);
-- --------------------------------------
CREATE TABLE ADMINISTRACION (
DNI VARCHAR(9) NOT NULL,
Cargo VARCHAR(25),
PRIMARY KEY(DNI)
);
-- - 
CREATE TABLE CAMAREROS (
DNI VARCHAR(9) NOT NULL,
Turno VARCHAR(25),
Años TINYINT,
DNI_encargado VARCHAR(9),
PRIMARY KEY(DNI)
);
-- -------------
CREATE TABLE COMEDORES (
CodigoC VARCHAR(5) NOT NULL,
Nombre VARCHAR(25),
Capacidad TINYINT,
Nmesas TINYINT,
Localizacion VARCHAR(25),
PRIMARY KEY(CodigoC)
);
-- --------------------
CREATE TABLE MESAS (
CodigoM VARCHAR(5) NOT NULL,
CodigoC VARCHAR(5) NOT NULL,
Nasientos TINYINT,
DNI_camarero VARCHAR(9),
PRIMARY KEY(CodigoM, CodigoC)
);
-- ------------------
CREATE TABLE Hacen (
CodigoM VARCHAR(5) NOT NULL,
CodigoC VARCHAR(5) NOT NULL,
Nreserva INT NOT NULL,
NasientosR INT,
PRIMARY KEY(CodigoM, CodigoC, Nreserva)
);
-- 
CREATE TABLE RESERVAS (
Nreserva INT NOT NULL,
Fhreserva DATETIME,
Nombre VARCHAR(25) NOT NULL,
Fhreservada DATETIME,
ComidaCena enum ('Comida', 'Cena'),
Npersonas SMALLINT,
Varios VARCHAR(100),
PRIMARY KEY(Nreserva)
);
-- 
CREATE TABLE FACTURAS (
NFactura INT NOT NULL,
FechaF DATETIME,
-- CodigoM VARCHAR(5),
-- CodigoC VARCHAR(5),
PRIMARY KEY(NFactura)
);
--
CREATE TABLE EMITEN (
NFactura INT NOT NULL,
CodigoM VARCHAR(5),
CodigoC VARCHAR(5),
PRIMARY KEY(NFactura,CodigoM,CodigoC)
);

-- 
CREATE TABLE Incluyen (
NFactura INT NOT NULL,
CodigoPl VARCHAR(5) NOT NULL,
Unidades TINYINT,
PRIMARY KEY(NFactura, CodigoPl)
);

--- 
CREATE TABLE PLATOS (
CodigoPl VARCHAR(5) NOT NULL,
Nombre VARCHAR(25),
Descripcion VARCHAR(50),
Tipo VARCHAR(25),
Precio DECIMAL(6,2),
PRIMARY KEY(CodigoPl)
);
-- 
CREATE TABLE Contienen (
CodigoPl VARCHAR(5) NOT NULL,
CodigoPr VARCHAR(5) NOT NULL,
Cantidad TINYINT,
PRIMARY KEY(CodigoPl, CodigoPr)
);
-- 
CREATE TABLE PRODUCTOS (
CodigoPr VARCHAR(5) NOT NULL,
Descripcion VARCHAR(50),
Stock TINYINT,
UnidadBase VARCHAR(25),
PrecioU DECIMAL(6,2),
Categoria VARCHAR(25),
CodigoPro VARCHAR(5),
PRIMARY KEY(CodigoPr)
);

--
CREATE TABLE PROVEEDORES (
CodigoPro VARCHAR(5) NOT NULL,
Direccion VARCHAR(50),
CP VARCHAR(5),
Telefono VARCHAR(9),
Fax VARCHAR(9),
Contacto VARCHAR(25),
PRIMARY KEY(CodigoPro)
);


ALTER TABLE COCINEROS
ADD CONSTRAINT FK_COC_DNI FOREIGN KEY(DNI) REFERENCES EMPLEADOS(DNI) ON DELETE CASCADE ON UPDATE CASCADE;
--
ALTER TABLE ADMINISTRACION
ADD CONSTRAINT FK_ADM_DNI FOREIGN KEY(DNI) REFERENCES EMPLEADOS(DNI) ON DELETE CASCADE ON UPDATE CASCADE;
--
ALTER TABLE CAMAREROS
ADD CONSTRAINT FK_CAM_DNI FOREIGN KEY(DNI) REFERENCES EMPLEADOS(DNI) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_CAM_DNI_ENCARGADO FOREIGN KEY(DNI_encargado) REFERENCES CAMAREROS(DNI) ON DELETE CASCADE ON UPDATE CASCADE;
--
ALTER TABLE MESAS
ADD CONSTRAINT FK_MES_CodC FOREIGN KEY(CodigoC) REFERENCES COMEDORES(CodigoC) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_MES_DNI_C FOREIGN KEY(DNI_camarero) REFERENCES CAMAREROS(DNI) ON DELETE SET NULL ON UPDATE CASCADE;
--
ALTER TABLE Hacen
  ADD CONSTRAINT Hac_FK_CodMCodC FOREIGN KEY(CodigoM,CodigoC) REFERENCES MESAS(CodigoM,CodigoC)
      ON DELETE NO ACTION ON UPDATE CASCADE,
ADD CONSTRAINT FK_Hac_NRes FOREIGN KEY(Nreserva) REFERENCES RESERVAS(Nreserva) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EMITEN
ADD CONSTRAINT FK_EMITEN_MESAS FOREIGN KEY(CodigoM,CodigoC) REFERENCES MESAS(CodigoM,CodigoC)
    ON DELETE restrict ON UPDATE CASCADE,
ADD CONSTRAINT FK_EMITEN_FACT FOREIGN KEY(nfACTURA) REFERENCES facturas(NFACtura)
   ON DELETE restrict ON UPDATE CASCADE;
--
ALTER TABLE Incluyen
  ADD CONSTRAINT FK_Inc_NFac FOREIGN KEY(NFactura) REFERENCES FACTURAS(NFactura) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT FK_Inc_CodPl FOREIGN KEY(CodigoPl) REFERENCES PLATOS(CodigoPl) ON DELETE CASCADE ON UPDATE CASCADE;
  --
ALTER TABLE Contienen
  ADD CONSTRAINT FK_Con_CodPl FOREIGN KEY(CodigoPl) REFERENCES PLATOS(CodigoPl) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT FK_Con_CodPr FOREIGN KEY(CodigoPr) REFERENCES PRODUCTOS(CodigoPr) ON DELETE CASCADE ON UPDATE CASCADE;
--
ALTER TABLE PRODUCTOS
ADD CONSTRAINT FK_PRO_CodPro FOREIGN KEY(CodigoPro) REFERENCES PROVEEDORES(CodigoPro)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- 2.1 Y 2.2
ALTER TABLE EMPLEADOS
ADD UNIQUE INDEX EMP_UNI_ApeNom (Apellidos, Nombre),-- INDEX O UNIQUE
ADD CONSTRAINT CHK_EMPL_FECH CHECK (FechAlta >='2022-06-01');
-- 2.3
ALTER TABLE CAMAREROS
MODIFY Turno ENUM('Mañana','Tarde','Noche');

-- 2.4
ALTER TABLE PROVEEDORES
  ADD COLUMN Apellidos VARCHAR(50) AFTER CodigoPro,
  ADD COLUMN Nombre VARCHAR(25) AFTER Apellidos;
-- 2.5;
-- ALTER TABLE MESAS
   --  ALTER COLUMN Nasientos SET DEFAULT 4;
ALTER TABLE MESAS MODIFY Nasientos tinyint DEFAULT 4;
-- 2.6
ALTER TABLE PRODUCTOS
  ADD UNIQUE uk_PRO_Cat (Categoria);
  
SHOW INDEX FROM PRODUCTOS;
-- 2.7
ALTER TABLE PRODUCTOS
      modify Stock SMALLINT UNSIGNED NOT NULL;
-- 2.8 TABLA PRODUCTOS
alter table productos DROP INDEX uk_PRO_Cat;

-- 2.9
ALTER TABLE PRODUCTOS
 DROP FOREIGN KEY FK_PRO_CodPro;
DROP TABLE PROVEEDORES; -- NO DEJA HASTA QUE NO BORREMOS LA FOREIGN KEYS
-- 2.10
-- drop database RestVillagarcia;
-- drop user xxxxx cascade -- - ORACLE










